import type { DiagramType } from "../models";

export interface SyntaxEntry {
  label: string;
  syntax: string;
}

export const SYNTAX_REFERENCE: Record<DiagramType, SyntaxEntry[]> = {
  flowchart: [
    { label: "Node", syntax: "A[Text]" },
    { label: "Round node", syntax: "A(Text)" },
    { label: "Diamond", syntax: "A{Text}" },
    { label: "Stadium", syntax: "A([Text])" },
    { label: "Cylinder", syntax: "A[(Text)]" },
    { label: "Arrow", syntax: "A --> B" },
    { label: "Dotted arrow", syntax: "A -.-> B" },
    { label: "Thick arrow", syntax: "A ==> B" },
    { label: "Arrow with text", syntax: "A -->|text| B" },
    { label: "Subgraph", syntax: "subgraph title\n  ...\nend" },
    { label: "Direction", syntax: "flowchart LR" },
    { label: "Style", syntax: "style A fill:#f9f" },
  ],
  sequence: [
    { label: "Participant", syntax: "participant Alice" },
    { label: "Actor", syntax: "actor Bob" },
    { label: "Solid arrow", syntax: "Alice->>Bob: message" },
    { label: "Dotted arrow", syntax: "Bob-->>Alice: reply" },
    { label: "Solid open", syntax: "Alice->Bob: msg" },
    { label: "Cross", syntax: "Alice-xBob: msg" },
    { label: "Note", syntax: "note over Alice: text" },
    { label: "Loop", syntax: "loop Every min\n  ...\nend" },
    { label: "Alt", syntax: "alt Condition\n  ...\nelse\n  ...\nend" },
    { label: "Activate", syntax: "activate Alice" },
    { label: "Autonumber", syntax: "autonumber" },
  ],
  class: [
    { label: "Class", syntax: "class Animal {\n  +String name\n  +move()\n}" },
    { label: "Inheritance", syntax: "Animal <|-- Dog" },
    { label: "Composition", syntax: "Car *-- Engine" },
    { label: "Aggregation", syntax: "Dept o-- Person" },
    { label: "Association", syntax: "A --> B" },
    { label: "Dependency", syntax: "A ..> B" },
    { label: "Realization", syntax: "A ..|> B" },
    { label: "Annotation", syntax: "<<interface>> Animal" },
    { label: "Visibility +", syntax: "+publicMethod()" },
    { label: "Visibility -", syntax: "-privateField" },
  ],
  state: [
    { label: "State", syntax: "State1" },
    { label: "Transition", syntax: "State1 --> State2" },
    { label: "Start", syntax: "[*] --> State1" },
    { label: "End", syntax: "State1 --> [*]" },
    { label: "Label", syntax: "s1 --> s2 : event" },
    { label: "Fork/Join", syntax: "state fork_state <<fork>>" },
    { label: "Choice", syntax: "state check <<choice>>" },
    { label: "Note", syntax: "note right of s1\n  text\nend note" },
    { label: "Composite", syntax: "state s1 {\n  ...\n}" },
    { label: "Concurrency", syntax: "--" },
  ],
  er: [
    { label: "Entity", syntax: "CUSTOMER {\n  string name\n}" },
    { label: "One-to-many", syntax: "A ||--o{ B : has" },
    { label: "One-to-one", syntax: "A ||--|| B : is" },
    { label: "Many-to-many", syntax: "A }o--o{ B : rel" },
    { label: "Zero or one", syntax: "|o" },
    { label: "Exactly one", syntax: "||" },
    { label: "Zero or more", syntax: "o{" },
    { label: "One or more", syntax: "|{" },
    { label: "Attribute types", syntax: "string, int, date" },
  ],
  gantt: [
    { label: "Title", syntax: "title My Project" },
    { label: "Date format", syntax: "dateFormat YYYY-MM-DD" },
    { label: "Axis format", syntax: "axisFormat %d/%m" },
    { label: "Section", syntax: "section Phase 1" },
    { label: "Task", syntax: "Task name :a1, 2024-01-01, 5d" },
    { label: "After", syntax: "Task 2 :after a1, 3d" },
    { label: "Active", syntax: "Task :active, a1, 5d" },
    { label: "Done", syntax: "Task :done, 5d" },
    { label: "Critical", syntax: "Task :crit, 3d" },
    { label: "Milestone", syntax: "Launch :milestone, 0d" },
  ],
  pie: [
    { label: "Title", syntax: 'pie title My Chart' },
    { label: "Slice", syntax: '"Label" : 42' },
    { label: "Show data", syntax: "pie showData" },
  ],
  git: [
    { label: "Commit", syntax: "commit" },
    { label: "Commit msg", syntax: 'commit id: "fix"' },
    { label: "Branch", syntax: "branch feature" },
    { label: "Checkout", syntax: "checkout feature" },
    { label: "Merge", syntax: "merge feature" },
    { label: "Cherry-pick", syntax: 'cherry-pick id: "abc"' },
    { label: "Tag", syntax: 'commit tag: "v1.0"' },
  ],
  mindmap: [
    { label: "Root", syntax: "root((Topic))" },
    { label: "Child", syntax: "  Child1" },
    { label: "Square", syntax: "  [Square]" },
    { label: "Rounded", syntax: "  (Rounded)" },
    { label: "Circle", syntax: "  ((Circle))" },
    { label: "Bang", syntax: "  ))Bang((" },
    { label: "Cloud", syntax: "  )Cloud(" },
    { label: "Hexagon", syntax: "  {{Hexagon}}" },
  ],
  timeline: [
    { label: "Title", syntax: "title My Timeline" },
    { label: "Period", syntax: "2023 : Event A : Event B" },
    { label: "Section", syntax: "section Year 2023" },
  ],
  unknown: [
    { label: "Flowchart", syntax: "flowchart TD" },
    { label: "Sequence", syntax: "sequenceDiagram" },
    { label: "Class", syntax: "classDiagram" },
    { label: "State", syntax: "stateDiagram-v2" },
    { label: "ER", syntax: "erDiagram" },
    { label: "Gantt", syntax: "gantt" },
    { label: "Pie", syntax: "pie" },
    { label: "Git Graph", syntax: "gitGraph" },
    { label: "Mindmap", syntax: "mindmap" },
    { label: "Timeline", syntax: "timeline" },
  ],
};
