import type { DiagramType } from "./diagram";

export interface SyntaxEntry {
  label: string;
  syntax: string;
}

export const SYNTAX_REFERENCE: Record<DiagramType, SyntaxEntry[]> = {
  flowchart: [
    { label: "Node", syntax: "A[Text]" },
    { label: "Round node", syntax: "A(Text)" },
    { label: "Diamond", syntax: "A{Text}" },
    { label: "Stadium", syntax: "A([Text])" },
    { label: "Cylinder", syntax: "A[(Text)]" },
    { label: "Arrow", syntax: "A --> B" },
    { label: "Dotted arrow", syntax: "A -.-> B" },
    { label: "Thick arrow", syntax: "A ==> B" },
    { label: "Arrow with text", syntax: "A -->|text| B" },
    { label: "Subgraph", syntax: "subgraph title\n  ...\nend" },
    { label: "Direction", syntax: "flowchart LR" },
    { label: "Style", syntax: "style A fill:#f9f" },
  ],
  sequence: [
    { label: "Participant", syntax: "participant Alice" },
    { label: "Actor", syntax: "actor Bob" },
    { label: "Solid arrow", syntax: "Alice->>Bob: message" },
    { label: "Dotted arrow", syntax: "Bob-->>Alice: reply" },
    { label: "Solid open", syntax: "Alice->Bob: msg" },
    { label: "Cross", syntax: "Alice-xBob: msg" },
    { label: "Note", syntax: "note over Alice: text" },
    { label: "Loop", syntax: "loop Every min\n  ...\nend" },
    { label: "Alt", syntax: "alt Condition\n  ...\nelse\n  ...\nend" },
    { label: "Activate", syntax: "activate Alice" },
    { label: "Autonumber", syntax: "autonumber" },
  ],
  class: [
    { label: "Class", syntax: "class Animal {\n  +String name\n  +move()\n}" },
    { label: "Inheritance", syntax: "Animal <|-- Dog" },
    { label: "Composition", syntax: "Car *-- Engine" },
    { label: "Aggregation", syntax: "Dept o-- Person" },
    { label: "Association", syntax: "A --> B" },
    { label: "Dependency", syntax: "A ..> B" },
    { label: "Realization", syntax: "A ..|> B" },
    { label: "Annotation", syntax: "<<interface>> Animal" },
    { label: "Visibility +", syntax: "+publicMethod()" },
    { label: "Visibility -", syntax: "-privateField" },
  ],
  state: [
    { label: "State", syntax: "State1" },
    { label: "Transition", syntax: "State1 --> State2" },
    { label: "Start", syntax: "[*] --> State1" },
    { label: "End", syntax: "State1 --> [*]" },
    { label: "Label", syntax: "s1 --> s2 : event" },
    { label: "Fork/Join", syntax: "state fork_state <<fork>>" },
    { label: "Choice", syntax: "state check <<choice>>" },
    { label: "Note", syntax: "note right of s1\n  text\nend note" },
    { label: "Composite", syntax: "state s1 {\n  ...\n}" },
    { label: "Concurrency", syntax: "--" },
  ],
  er: [
    { label: "Entity", syntax: "CUSTOMER {\n  string name\n}" },
    { label: "One-to-many", syntax: "A ||--o{ B : has" },
    { label: "One-to-one", syntax: "A ||--|| B : is" },
    { label: "Many-to-many", syntax: "A }o--o{ B : rel" },
    { label: "Zero or one", syntax: "|o" },
    { label: "Exactly one", syntax: "||" },
    { label: "Zero or more", syntax: "o{" },
    { label: "One or more", syntax: "|{" },
    { label: "Attribute types", syntax: "string, int, date" },
  ],
  gantt: [
    { label: "Title", syntax: "title My Project" },
    { label: "Date format", syntax: "dateFormat YYYY-MM-DD" },
    { label: "Axis format", syntax: "axisFormat %d/%m" },
    { label: "Section", syntax: "section Phase 1" },
    { label: "Task", syntax: "Task name :a1, 2024-01-01, 5d" },
    { label: "After", syntax: "Task 2 :after a1, 3d" },
    { label: "Active", syntax: "Task :active, a1, 5d" },
    { label: "Done", syntax: "Task :done, 5d" },
    { label: "Critical", syntax: "Task :crit, 3d" },
    { label: "Milestone", syntax: "Launch :milestone, 0d" },
  ],
  pie: [
    { label: "Title", syntax: 'pie title My Chart' },
    { label: "Slice", syntax: '"Label" : 42' },
    { label: "Show data", syntax: "pie showData" },
  ],
  git: [
    { label: "Commit", syntax: "commit" },
    { label: "Commit msg", syntax: 'commit id: "fix"' },
    { label: "Branch", syntax: "branch feature" },
    { label: "Checkout", syntax: "checkout feature" },
    { label: "Merge", syntax: "merge feature" },
    { label: "Cherry-pick", syntax: 'cherry-pick id: "abc"' },
    { label: "Tag", syntax: 'commit tag: "v1.0"' },
  ],
  mindmap: [
    { label: "Root", syntax: "root((Topic))" },
    { label: "Child", syntax: "  Child1" },
    { label: "Square", syntax: "  [Square]" },
    { label: "Rounded", syntax: "  (Rounded)" },
    { label: "Circle", syntax: "  ((Circle))" },
    { label: "Bang", syntax: "  ))Bang((" },
    { label: "Cloud", syntax: "  )Cloud(" },
    { label: "Hexagon", syntax: "  {{Hexagon}}" },
  ],
  timeline: [
    { label: "Title", syntax: "title My Timeline" },
    { label: "Period", syntax: "2023 : Event A : Event B" },
    { label: "Section", syntax: "section Year 2023" },
  ],
  c4: [
    { label: "Person", syntax: 'Person(alias, "Label", "Desc")' },
    { label: "System", syntax: 'System(alias, "Label", "Desc")' },
    { label: "External System", syntax: 'System_Ext(alias, "Label")' },
    { label: "Container", syntax: 'Container(alias, "Label", "Tech")' },
    { label: "Container DB", syntax: 'ContainerDb(alias, "Label", "Tech")' },
    { label: "Component", syntax: 'Component(alias, "Label", "Tech")' },
    { label: "System Boundary", syntax: 'System_Boundary(id, "Label") { }' },
    { label: "Relationship", syntax: 'Rel(from, to, "Label", "Tech")' },
  ],
  architecture: [
    { label: "Group", syntax: "group name(icon)[Label]" },
    { label: "Service", syntax: "service name(icon)[Label] in group" },
    { label: "Junction", syntax: "junction name in group" },
    { label: "Connect", syntax: "a:R --> L:b" },
    { label: "Directions", syntax: "T (top) B (bottom) L (left) R (right)" },
  ],
  block: [
    { label: "Columns", syntax: "columns 3" },
    { label: "Block", syntax: 'a["Label"]:2' },
    { label: "Group", syntax: "block:group:2\n  ...\nend" },
    { label: "Space", syntax: "space:1" },
  ],
  requirement: [
    { label: "Requirement", syntax: "requirement name {\n  id: 1\n  text: desc\n  risk: high\n  verifymethod: test\n}" },
    { label: "Element", syntax: "element name {\n  type: module\n  docref: doc.md\n}" },
    { label: "Satisfies", syntax: "elem - satisfies -> req" },
    { label: "Traces", syntax: "elem - traces -> req" },
  ],
  quadrant: [
    { label: "Title", syntax: "title My Chart" },
    { label: "X axis", syntax: "x-axis Low --> High" },
    { label: "Y axis", syntax: "y-axis Low --> High" },
    { label: "Quadrant labels", syntax: "quadrant-1 Label" },
    { label: "Point", syntax: "Item: [0.5, 0.7]" },
  ],
  sankey: [
    { label: "Flow", syntax: "Source,Target,Value" },
  ],
  xychart: [
    { label: "Title", syntax: 'title "Chart Title"' },
    { label: "X axis", syntax: "x-axis [A, B, C]" },
    { label: "Y axis", syntax: 'y-axis "Label" 0 --> 100' },
    { label: "Bar", syntax: "bar [10, 20, 30]" },
    { label: "Line", syntax: "line [10, 20, 30]" },
  ],
  radar: [
    { label: "Title", syntax: 'title "Chart"' },
    { label: "Axes", syntax: "axis A, B, C, D" },
    { label: "Curve", syntax: 'curve a["Label"] { 80, 60, 90, 70 }' },
  ],
  kanban: [
    { label: "Column", syntax: "Column Name" },
    { label: "Card", syntax: "  Card title" },
    { label: "Metadata", syntax: "  Card @{ assigned: 'user' }" },
  ],
  journey: [
    { label: "Title", syntax: "title My Journey" },
    { label: "Section", syntax: "section Phase" },
    { label: "Task", syntax: "Task name: 5: Actor1, Actor2" },
  ],
  packet: [
    { label: "Field", syntax: '0-15: "Field Name"' },
    { label: "Single bit", syntax: '7: "Flag"' },
  ],
  unknown: [
    { label: "Flowchart", syntax: "flowchart TD" },
    { label: "Sequence", syntax: "sequenceDiagram" },
    { label: "Class", syntax: "classDiagram" },
    { label: "State", syntax: "stateDiagram-v2" },
    { label: "ER", syntax: "erDiagram" },
    { label: "Gantt", syntax: "gantt" },
    { label: "Pie", syntax: "pie" },
    { label: "Git Graph", syntax: "gitGraph" },
    { label: "Mindmap", syntax: "mindmap" },
    { label: "Timeline", syntax: "timeline" },
    { label: "C4 Context", syntax: "C4Context" },
    { label: "Architecture", syntax: "architecture-beta" },
    { label: "Block", syntax: "block-beta" },
    { label: "Requirement", syntax: "requirementDiagram" },
    { label: "Quadrant", syntax: "quadrantChart" },
    { label: "Sankey", syntax: "sankey-beta" },
    { label: "XY Chart", syntax: "xychart-beta" },
    { label: "Radar", syntax: "radar-beta" },
    { label: "Kanban", syntax: "kanban" },
    { label: "Journey", syntax: "journey" },
    { label: "Packet", syntax: "packet-beta" },
  ],
};
